KeyError: 'Open'
Traceback:
File "/nix/store/rv55xcjw63fcfb8p9qd85s8hfxjry3w5-python3.11-streamlit-1.34.0/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
File "/home/runner/workspace/main.py", line 721, in <module>
    main()
File "/home/runner/workspace/main.py", line 438, in main
    metrics = st.session_state.model.train(stock_name=stock_name,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/workspace/core/ppo_fin_model.py", line 54, in train
    self.agent.train(total_timesteps=total_timesteps, callback=callback)
File "/home/runner/workspace/core/base_agent.py", line 274, in train
    self.model.learn(total_timesteps=total_timesteps, callback=callback)
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/stable_baselines3/ppo/ppo.py", line 315, in learn
    return super().learn(
           ^^^^^^^^^^^^^^
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 287, in learn
    total_timesteps, callback = self._setup_learn(
                                ^^^^^^^^^^^^^^^^^^
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/stable_baselines3/common/base_class.py", line 423, in _setup_learn
    self._last_obs = self.env.reset()  # type: ignore[assignment]
                     ^^^^^^^^^^^^^^^^
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 77, in reset
    obs, self.reset_infos[env_idx] = self.envs[env_idx].reset(seed=self._seeds[env_idx], **maybe_options)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/stable_baselines3/common/monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/workspace/environment/simple_trading_env.py", line 122, in reset
    observation = self._get_observation()
                  ^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/workspace/environment/simple_trading_env.py", line 74, in _get_observation
    data['Open'],
    ~~~~^^^^^^^^
File "/nix/store/a4rihhw5j33rswdlhl9fll9jx5gk8bgi-python3.11-pandas-2.2.1/lib/python3.11/site-packages/pandas/core/series.py", line 1112, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
File "/nix/store/a4rihhw5j33rswdlhl9fll9jx5gk8bgi-python3.11-pandas-2.2.1/lib/python3.11/site-packages/pandas/core/series.py", line 1228, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
File "/nix/store/a4rihhw5j33rswdlhl9fll9jx5gk8bgi-python3.11-pandas-2.2.1/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err